In [2]:
x='aswin'
y=x[1:3]
print(y)

sw


In [29]:
m = ([1,2,4],
    [3,4,5],
    [3,2,1])

print(m[1])
print(f"first element {m[0][0]}")
print(f"first 2 rows {m[0:2]}")
#print(m[0:2,:]) works only in np

print(f"first 2 elements in the first 2 rows {[row[0:2] for row in m[0:2]]}")
print(f"first 2 elements in the first 2 cols {[[row[0], row[1]] for row in m]}")


[3, 4, 5]
first element 1
first 2 rows ([1, 2, 4], [3, 4, 5])
first 2 elements in the first 2 rows [[1, 2], [3, 4]]
first 2 elements in the first 2 cols [[1, 2], [3, 4], [3, 2]]


In [40]:
# numpy
import numpy as np

m = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"first two rows {m[0:2, :]}")
print(f"first two cols {m[:, 0:2]}")
print(f"first 2 elements in first 2 rows \n {m[0:2,0:2]}")
print(f"last row and last col \n {m[-1,:], m[:,-1]}")


first two rows [[1 2 3]
 [4 5 6]]
first two cols [[1 2]
 [4 5]
 [7 8]]
first 2 elements in first 2 rows 
 [[1 2]
 [4 5]]
last row and last col 
 (array([7, 8, 9]), array([3, 6, 9]))


In [41]:
# In context of image processing

img.shape        # (H, W) or (H, W, C)
img.dtype        # uint8, float32, etc.
img.ndim         # 2 for grayscale, 3 for color
img.size         # total number of elements
img[y1:y2, x1:x2, :] 

#channel operations
r = img[:, :, 0]
g = img[:, :, 1]
b = img[:, :, 2]

img = img.astype(np.uint8)


NameError: name 'img' is not defined